name: Release

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v7
    - name: Generate changelog for release
      run: ./package/extract-changelog.sh "$GITHUB_REF_NAME" | tee release-notes.md
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        bodyFile: "release-notes.md"
